name: VPS-Windows

on: [workflow_dispatch, push]

jobs:
  Starting-Windows:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
      - name: Download Ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
      - name: Extract Ngrok Archive
        run: Expand-Archive ngrok.zip
      - name: Auth
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
      - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 5
      - name: Set Pwd and Start tunnel
        run: |
           # Set ngrok password permanent (uesing):
           $Pwd = "Kingsmanvn007"
           # Set ngrok password random:
           # $Pwd = -join ('abcdefghkmnrstuvwxyzABCDEFGHKLMNPRSTUVWXYZ23456789$%&*#'.ToCharArray() | Get-Random -Count 32)
           Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $Pwd -Force)
           Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389"
           Start-Sleep -s 10
           $Response = ConvertFrom-Json(Invoke-WebRequest -Uri "http://127.0.0.1:4040/api/tunnels")
           Start-Sleep -s 1
           $URLString = $Response.tunnels.public_url
           $Fulladdress = ($URLString -split "tcp://")[1]
           $Rdp = "full address:s:$Fulladdress`nusername:s:runneradmin"
           $ProgressPreference = 'Continue'
           echo "RDP INFOMATION"
           echo "Fulladress: $Fulladdress"
           echo "User: runneradmin"
           echo "Pwd: $Pwd"
           Start-Sleep -s 43200

  Del-run:
    needs: Starting-Windows
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
